import type { Metadata } from "next";
import localFont from "next/font/local";
import { Navbar } from "@/components/Navbar";
import "./globals.css";
import FixedBookAppointment from "@/components/sideComponents/FixedBookAppointment";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "HPS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="w-full z-1 dark:bg-white bg-white  dark:bg-grid-black/[0.05] bg-grid-black/[0.1] relative flex flex-col items-center justify-center">
          {/* Radial gradient for the container to give a faded look */}
          {/* <div className="absolute pointer-events-none inset-0 flex items-center justify-center dark:bg-white bg-white [mask-image:radial-gradient(ellipse_at_center,transparent_60%,white)]"></div> */}
          <Navbar />
          <FixedBookAppointment />
          {children}
        </div>
      </body>
    </html>
  );
}
